%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\UO257551\Desktop\CEMENTERA\Motor_2\AxeY\1663664502-5000Hz-DE.csv
%
% Auto-generated by MATLAB on 27-Sep-2022 09:48:51

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
HzDE = readtable("C:\Users\UO257551\Desktop\CEMENTERA\Motor_2\AxeY\1663664502-5000Hz-DE.csv", opts);


%% Clear temporary variables
clear opts